### ISSUE TITLE
Is JDK 1.8 support been added to the new version 1.2 

### ISSUE THREAD

**Issue by sattishv** [krzysztofslusarski/jvm-gc-logs-analyzer#31]
Hi,

Does the new version of of  jvm-gc-logs-analyzer 1.2 has the support to parse verbosegc logs created using JDK 1.8 versions.
Could you please confirm

thanks
Sattish

**Comment by krzysztofslusarski** [comment]
No, it doesn't. It may work on standalone version, but it is by accident, not by design. I have a plan to investigate possibility of using https://github.com/microsoft/gctoolkit to parse the GC part of the logs. This will be done while merging this project into https://github.com/krzysztofslusarski/jvm-profiling-toolkit - this is a pretty big challange, I cannot promise any deadline on it. For GC logs at JDK8 I recommend use of easygc for now.
